### ISSUE TITLE
NameError: uninitialzed constant DiscourseBackupToDropbox::Synchronizer

### ISSUE THREAD

**Issue by dschaper** [xfalcox/discourse-backups-to-dropbox#14]
Discourse running in Multi-Container Docker configuration, version v1.9.0.beta7 +18 (latest). 

Bootstrapping the web_only container throws the following error:

```
I, [2017-08-19T13:01:14.690393 #15]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
rake aborted!
NameError: uninitialized constant DiscourseBackupToDropbox::Synchronizer
/var/www/discourse/plugins/discourse-backups-to-dropbox/lib/dropbox_synchronizer.rb:2:in `<module:DiscourseBackupToDropbox>'
/var/www/discourse/plugins/discourse-backups-to-dropbox/lib/dropbox_synchronizer.rb:1:in `<top (required)>'
/var/www/discourse/plugins/discourse-backups-to-dropbox/plugin.rb:22:in `block in activate!'
/var/www/discourse/lib/plugin/instance.rb:241:in `block in notify_after_initialize'
/var/www/discourse/lib/plugin/instance.rb:239:in `each'
/var/www/discourse/lib/plugin/instance.rb:239:in `notify_after_initialize'
/var/www/discourse/config/application.rb:216:in `each'
/var/www/discourse/config/application.rb:216:in `block in <class:Application>'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:44:in `each'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `public_send'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `method_missing'
/var/www/discourse/config/environment.rb:5:in `<top (required)>'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:328:in `require_environment!'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by olirogers** [comment]
I had this issue too. Looks like it is now fixed, at least on 2ea0e7a656d60da679bd2110a09308d19b56f0f5 (current master).
